### ISSUE TITLE
Question on student eviction

### ISSUE THREAD

**Issue by Vectorial1024** [algernon-A/Lifecycle-Rebalance-Revisited#20]
I am using ModTools for debugging other things, and have noticed a lot of debug messages that looks like this:

`Lifecycle Rebalance Revisited: evicting elementary school student 963344 at age 178.`

I am having difficulty getting my buildings upgraded because they always want more education, but I am not sure why this kind of eviction are happening. Could this be I am using the Real Time mod? There is an option called "Better aging and birth rate" at Real Time and I have enabled it.

**Comment by algernon-A** [comment]
No, the Real Time mod settings have no effect when this mod is in operation (Real Time deliberately disables itself).

Those messages are part of a routine check the mod performs to ensure that any school students that didn't properly graduate are removed from the school.  This situation can be caused by other mods interfering with school or ageing processes, and this is the fix for that (otherwise students can be 'stuck' at school for the rest of their lives, and never find employment etc.).  These messages are an indication that something has gone wrong with your game, but the mod is detecting and fixing that for you.
